# Generated by Django 3.1.4 on 2020-12-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courses',
            field=models.CharField(choices=[('Engineering', (('Software Engineering', 'SE'), ('Computer Engineering', 'CE'), ('Electrical Engineering', 'EE'))), ('Commerce', (('Bachelor of Business Administration', 'BBA'), ('Chartered Accountancy', 'CA'))), ('Medical', (('Neuroscience', 'NS'), ('Bachelor of Medicine, Bachelor of Surgery', 'MBBS')))], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], max_length=50),
        ),
    ]
